// CONFIGURACAO OPCIONAL DO FIREBASE PARA CONTA GOOGLE + FIRESTORE.
// NAO COLOQUE CHAVES PRIVADAS, SERVICE ACCOUNT OU SENHAS NESTE ARQUIVO.
// O firebaseConfig DA WEB PODE SER PUBLICO; A PROTECAO REAL FICA NAS REGRAS DO FIRESTORE.
window.MINHA_LISTA_FIREBASE_CONFIG = null;

// EXEMPLO:
// window.MINHA_LISTA_FIREBASE_CONFIG = {
//   apiKey: "SUA_API_KEY",
//   authDomain: "SEU-PROJETO.firebaseapp.com",
//   projectId: "SEU-PROJETO",
//   storageBucket: "SEU-PROJETO.appspot.com",
//   messagingSenderId: "SEU_SENDER_ID",
//   appId: "SEU_APP_ID"
// };
